### ISSUE TITLE
Libre Link Upload&Download integration 

### ISSUE THREAD

**Issue by yoshimo** [creepymonster/GlucoseDirectApp#120]
For relatives and doctors that are not as technically capable and willing to use opensource software, it would be great if you could interface directly with the Abbott database.
Being a Libre Linkup partner to watch over your relatives glucose levels or send your own measurements to your linkup partners like wife, husband, boyfriend or doctor would be great.

**Comment by creepymonster** [comment]
I don't want to include this feature, at least not as long as there is no semi-official way. Otherwise it is a guarantee for big trouble (possibly banned user accounts or ban from TestFlight). Even if I find the possibility very useful, I can also understand the anger of the manufacturer.

Many greetings

**Comment by yoshimo** [comment]
What do you mean by "semi-official" in this context?

**Comment by creepymonster** [comment]
I thought I had seen something about a possibility of CSV or Excel import. But maybe it was only an export from LibreView.

I could also imagine that a Nightscout plugin could close the gap quite well.
